In [3]:
from git import *
from comp import *
from clf import *


#p1=get_pull('laravel/framework','4138')
#p2=get_pull('laravel/framework','2678')

#s = 'facebook/react 3969 3807'

#s = 'facebook/react 12488	10255'

#s = 'facebook/react 11868	4426'

#s='facebook/react	12770	12311'

# s = 'elastic/elasticsearch 27744 27600'

# s = 'CleverRaven/Cataclysm-DDA 10005 8445'

# s = 'Homebrew/homebrew-cask	48598	35654'

# s = 'kubernetes/kubernetes 50018 55744'

s = 'facebook/react 8996 8815'

repo, n1, n2 = s.split()

init_model_with_repo(repo)

p1=get_pull(repo, n1)
p2=get_pull(repo, n2)

#print(fetch_pr_info(p1))
#print(fetch_pr_info(p2))

# print(get_numbers(p1['body']), get_numbers(p2['body']))
#calc_sim(p1,p2)

'''
print(p1['body'])
print(p2['body'])

A=p1
print(get_version_numbers(A["title"] + ' ' + A['body']))
   
A=p2
print(get_version_numbers(A["title"] + ' ' + A['body']))
'''

vet = get_pr_sim(p1,p2)

print(vet)


c = classify()
ret = c.predict_proba([get_pr_sim_vector(p1,p2)])[0][1]

print(ret)


#print(get_topK('elastic/elasticsearch', '6287', 10, True))

#print(get_topK('facebook/react', '1702', 10, True))


init nlp model with facebook/react data!
model already exists!
init nlp model for text successfully!
model already exists!
init nlp model for code successfully!
{'title': [0.3072585887396503], 'desc': [0.4508086834858737], 'code': [1.0, 1.0], 'file_list': [1.0, 1], 'location': [0.6666666666666666, 0.6666666666666666], 'pattern': [-1]}
Data Loading.........
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/first_msr_pairs.txt
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/second_msr_pairs.txt
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/first_nondup.txt
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/second_nondup.txt
--------------------------
Model: training_set 50618 testing_set 50737 feature_length= 9
------ model:  boost ------
[0.22  0.42  0.105 0.005 0.06  0.035 0.045 0.045 0.065]
Mean Accuracy: 0.9942645406705166
Average precision score: 0.9191
F1 score: 0.8643
0.6226046505860838


In [ ]:
import simulate_part_pr



s = 'angular/angular.js	8492	8233'
repo, n1, n2 = s.split()

init_model_with_repo(repo)

simulate_part_pr.simulate(repo, n1, n2)


In [ ]:
from detect import *
 

print(get_topK('symfony/symfony', '10425', 10, True)) 


In [ ]:
from git import *

repos = open('data/msr_repo_list.txt').readlines()

# repo = 'cocos2d/cocos2d-x'

for repo in repos:

    pulls = get_pull_list(repo, False)

    num, tot = 0, 0
    for pull in pulls:
        tot += 1
        if len(get_pr_numbers(str(pull['title']) + str(pull['body']))) > 0:
            num += 1
    print(repo.strip(), ':', 1.0 * num / tot)


In [ ]:
from main import *

# init_model_with_repo('Ultimaker/Ultimaker2Marlin')
init_model_with_repo('MarlinFirmware/Marlin')
get_sim_vector(get_pull('Ultimaker/Ultimaker2Marlin', '50'), get_pull('MarlinFirmware/Marlin', '1402'))

In [ ]:
from main import *

# init_model_with_repo('ceph/ceph')

p1 = get_pull('hashicorp/terraform', '6827')
t = get_another_pull(p1)
print(type(t[0]))
print(get_another_pull(p1))

print(type(p1["number"]))
'''
p2 = get_pull('ceph/ceph', '10427')
print(get_BoW(p1["title"]))
print(get_BoW(p2["title"]))

print(get_sim('ceph/ceph', '10438', '10427'))

print(check_pattern(p1, p2))
'''

In [ ]:
from main import *

# init_model_with_repo('Ultimaker/Ultimaker2Marlin')
init_model_with_repo('MarlinFirmware/Marlin')
get_sim_vector(get_pull('Ultimaker/Ultimaker2Marlin', '50'), get_pull('MarlinFirmware/Marlin', '1402'))

In [ ]:
from main import *

# init_model_with_repo('Ultimaker/Ultimaker2Marlin')
init_model_with_repo('MarlinFirmware/Marlin')
get_pr_sim_vector(get_pull('Ultimaker/Ultimaker2Marlin', '50'), get_pull('MarlinFirmware/Marlin', '1402'))

In [ ]:
import main
# main.init_model_with_repo('facebook/react')
# main.get_sim('facebook/react', '12767', '11770')

main.init_model_with_repo('facebook/react')
main.get_sim('facebook/react', '466', '433')



In [ ]:
import main
main.init_model_with_repo('facebook/react')
main.get_sim('facebook/react', '12767', '11770')



In [ ]:
import main
import git

%time main.init_model_with_pulls(git.get_pull_list('MarlinFirmware/Marlin'))

'''
import main
main.init_model_with_repo('SignalR/SignalR')
main.get_sim('SignalR/SignalR', '3094', '3862')
'''

In [ ]:
import re
def camel_case_split(identifier):
    matches = re.finditer('.+?(?:(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])|$)', identifier)
    return [m.group(0) for m in matches]

print(camel_case_split('AasAdsaB'))
print(camel_case_split('dasAdsaBcdas'))
print(camel_case_split('ARM64'))

print(camel_case_split('321jca+dsad321_dsaAz'))

In [ ]:
import main
c = main.classify() # all

"""
with open('tmp/1.txt') as f:
    for l in f.readlines():
        if len(l)<=3:
            continue
        p, n1, n2 = l.split()
        
        t = main.get_sim(p, n1, n2)
        
        print(c.predict([t])[0], p, n1, n2, t)
"""

with open('')
X_test = localfile_tool.get_file('data/improve_false_data_msr_positive_pairs_lsi_X.json')
y_test = localfile_tool.get_file('data/improve_false_data_msr_positive_pairs_lsi_y.json')

acc = c.score(X_test, y_test)
print('Mean Accuracy:', acc)

# c.predict()


In [ ]:
import main
main.get_sim('mozilla-b2g/gaia', '2420', '2459')

In [ ]:
import main
p = main.get_pull('mozilla-b2g/gaia', '2420')
f = fetch_pr_info(p)
print([x["name"] for x in f])


In [ ]:
from main import *
from git import *
from comparer import *

repo = 'spring-projects/spring-framework'
init_model_with_pulls([], repo.replace('/','_') + '_all')
# init_model_with_repo(repo)

x = 'Changed min accepted day of month to 1'
y = 'Support for the last day in month cron expression'

'''
x = 'Tokenizer - removing unnecessary boxing'
y = 'Tokenizer - removes unnecessary boxing of char'
'''

%timeit text_sim(x,y)
# text_sim(x,y)
'''
print(model.get_tfidf(get_BoW(x)))
print(model.get_tfidf(get_BoW(y)))
c = set(get_BoW(x)) & set(get_BoW(y))
print(model.get_idf_sum(c))
'''

In [ ]:
from util import localfile
ps = localfile.get_file('data/msr_positive_pairs_feature_vector_all_clues_with_text_lsi_code_bow_X.json')
for p in ps:
    if p[0] >= 0.9:
        print(p[0], p[2])
    

In [ ]:
from git import *
from comp import *

def func(file):

    num = 0
    tot = 0
    with open(file) as f:
        for f0 in f.readlines():
            r, n1, n2 = f0.split()
            p1 = get_pull(r, n1)
            p2 = get_pull(r, n2)
            s1 = get_tokens(p1['title'])
            s2 = get_tokens(p2['title'])
            if (set(s1) & set(s2)):
                t = len(s1) + len(s1)
                num += 1
                tot += t

    print (1.0 * tot / num)
    
func('data/clf/small_part_negative.txt')
func('data/clf/msr_positive_pairs.txt')

                                    
'''                      
with open('data/clf/manual_label_false.txt') as f:
    for t in f.readlines():
        r, n1, n2 = t.split()
        p1 = get_pull(r, n1)
        p2 = get_pull(r, n2)
        t = set(get_tokens(p1['title'])) & set(get_tokens(p2['title']))
        if t:
            print(t)
'''     

In [ ]:

from git import *
from comp import *

r = 'laravel/framework'

ps = get_repo_info(r, 'pull')
tot = 0
cnt = 0
for p in ps:
    cnt += 1
    print(cnt)

    file_list = fetch_pr_info(p)
    for file in file_list:
        tot += len(file["add_code"]) + len(file["del_code"])

print('tot=', tot)



In [ ]:
from numpy import array
from numpy import median
from clf import *


def q(a):
    print('\t'.join(['{0:0.4f}'.format(1.0 * sum(a[:,i]) / len(a)) for i in range(len(a[0]))]))
    
    # print('\t'.join(['{0:0.4f}'.format(median(a[:,i])) for i in range(len(a[0]))]))
    
f = []
no = []
yes = []
for s in dataset:
    new_X, new_y = get_feature_vector(s[0], s[1], model_data_renew_flag, model_data_save_path_suffix)
    
    if ('true' in s[0]) or ('msr' in s[0]):
        yes += new_X
    else:
        no += new_X

no = array(no)
yes = array(yes)

# q(no)
# q(yes)


# sum(L) / float(len(L))

    

In [ ]:
from clf import *
from comp import *

last = None
q = []

cnt = {}

with open('/home/luyao/PR_get/INTRUDE/data/clf/manual_label_true.txt') as f:
    for pair in f.readlines():
        r, n1, n2 = pair.split()
        
        if r != last:
            last = r
            # init_model_with_repo(r)
            print('cnt', r)
            cnt = {}
            ps = get_repo_info(r, 'pull')
            for p in ps:
                for x in get_tokens(p['title']):
                    if x not in cnt:
                        cnt[x] = 0
                    cnt[x] += 1
        
        p1 = get_pull(r, n1)
        p2 = get_pull(r, n2)
        
        def add(p):
            x = [cnt.get(word, 0) for word in get_tokens(p['title'])]
            q.append(sum(x) / len(x))
            
        add(p1)
        add(p2)

print(sum(q) / len(q))



In [ ]:
from clf import *
from comp import *

init_model_with_repo('bitcoin/bitcoin')
p1 = get_pull('peercoin/peercoin', '219')
p2 = get_pull('bitcoin/bitcoin', '5509')

print(get_pr_sim_vector(p1, p2))


In [ ]:

files = [
'/home/luyao/PR_get/INTRUDE/data/clf/manual_label_false.txt',
#'/home/luyao/PR_get/INTRUDE/data/clf/manual_label_true.txt',
'/home/luyao/PR_get/INTRUDE/data/clf/openpr_label_false.txt',
#'/home/luyao/PR_get/INTRUDE/data/clf/openpr_label_true.txt'
]

for file in files:
    for t in open(file).readlines():
        r, n1, n2 = t.split()
        p1 = get_pull(r, n1)
        p2 = get_pull(r, n2)
        
        def add(p1):
            file_list = fetch_pr_info(p1)
            return sum([x["LOC"]['add'] for x in file_list])
        def dele(p1):
            file_list = fetch_pr_info(p1)
            return sum([x["LOC"]['del'] for x in file_list])
        
        
        print(t.strip(), 'line=', '+%d,-%d' % (add(p1), dele(p1)) , '\t', '+%d,-%d' % (add(p2), dele(p2)))
        print(p1['title'])
        print(p2['title'])
        
        print('------')
    
        '''
        file_list = fetch_pr_info(p1)
        if len(file_list) <= 10:
            #print(p1['title'], ':', [x['name'] for x in file_list])
            t = sum([x["LOC"]['add'] for x in file_list])
            if t <= 10:
                print(r, n1, n2, p1['title'], ':', t)
        ''' 
            

In [ ]:
files = [
    '/home/luyao/PR_get/INTRUDE/data/clf/small_part_msr.txt',
    '/home/luyao/PR_get/INTRUDE/data/clf/rly_false_pairs.txt'
]

from datetime import datetime, timedelta

def get_time(t):
    return datetime.strptime(t, "%Y-%m-%dT%H:%M:%SZ")

from git import *

for file in files:
    q = []
    for t in open(file).readlines():
        r, n1, n2 = t.split()
        p1 = get_pull(r, n1)
        p2 = get_pull(r, n2)
        
        d = abs((get_time(p1['created_at']) - get_time(p2['created_at'])).days)
        q.append(d)

    print(sum(q) / len(q))
    print(sorted(q))


In [ ]:
from git import *
# % timeit t = get_pull(, )

% timeit t = api.get('repos/%s/pulls/%s' % ('facebook/react', '12391'))

print(t)

In [1]:
from detect import *
print(get_topK('laravel/framework', '22057', 10, True))


text_sim_type= lsi
code_sim_type= tfidf
extract_sim_type= ori_and_overlap
Data Type: ok_text_lsi_code_tfidf_ori_and_overlap
Data Loading.........
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/first_msr_pairs.txt
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/second_msr_pairs.txt
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/first_nondup.txt
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/second_nondup.txt
--------------------------
Model: training_set 50618 testing_set 50737 feature_length= 9
------ model:  boost ------
[0.22  0.42  0.105 0.005 0.05  0.045 0.035 0.055 0.065]
Mean Accuracy: 0.9942645406705166
Average precision score: 0.9191
F1 score: 0.8643
init nlp model with laravel/framework data!
model already exists!
init nlp model for text successfully!
model already exists!
init nlp model for code successfully!
progress =  0.1305293691080493
progress =  0.22480058013052936
progress =  0.39158810732414795
progress =  0.43509789702683105
progress =  0.5

In [5]:
from git import *
from comp import *
from clf import *

s = 'laravel/framework 18705 17589'

repo, n1, n2 = s.split()

init_model_with_repo(repo)

p1=get_pull(repo, n1)
p2=get_pull(repo, n2)

vet = get_pr_sim(p1,p2)

print(vet)

c = classify()
ret = c.predict_proba([get_pr_sim_vector(p1,p2)])[0][1]

print(ret)

init nlp model with laravel/framework data!
model already exists!
init nlp model for text successfully!
model already exists!
init nlp model for code successfully!
{'title': [0.8746197528924626], 'desc': [0.0], 'code': [0.6404730300257933, 0.6404730300257933], 'file_list': [1.0, 1], 'location': [0.0, 0.0], 'pattern': [0]}
Data Loading.........
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/first_msr_pairs.txt
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/second_msr_pairs.txt
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/first_nondup.txt
Model Data Input= /home/luyao/PR_get/INTRUDE/data/clf/second_nondup.txt
--------------------------
Model: training_set 50618 testing_set 50737 feature_length= 9
------ model:  boost ------
[0.22  0.42  0.105 0.005 0.045 0.05  0.035 0.055 0.065]
Mean Accuracy: 0.9942645406705166
Average precision score: 0.9191
F1 score: 0.8643
0.5601423492316505
